name: Deploy MkDocs

on:
  push:
    branches:
      - main  

permissions:
  contents: read  
  pages: write    
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" 

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs-material mkdocs-minify-plugin mkdocs-glightbox mkdocs-awesome-pages-plugin pymdown-extensions

      - name: Build and Deploy MkDocs
        run: |
          mkdocs gh-deploy --force
