codecov:
  notify:
    require_ci_to_pass: yes
    after_n_builds: 2

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default