site_name: Nexios
site_description: A modern backend framework for building scalable and efficient web applications.
site_author: Dunamis
site_url: https://nexios.example.com
repo_url: https://github.com/techwithdunamix/nexios

# Theme Configuration
theme:
  name: material
  favicon: logo.png
  logo: logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: "deep-purple"
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: "deep-purple"
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github

# Navigation Structure
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: introduction.md
      - Installation: installation.md
      - Hello World: hello_world.md
      - application: application.md
      - configuration: configs.md
      - Basic Routing: basic_routing.md
  - Core Features:
      - Request Object: core-features/request-object.md
      - Response Object: core-features/response-object.md
      - Routing : core-features/routing.md
      - Middleware: core-features/middleware.md
      - Exceptions: core-features/exceptions.md
      - WebSocket Support: core-features/websocket.md
      - Validation: core-features/validator.md
      - Session: core-features/session.md
  
 
# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
  - glightbox
  - awesome-pages  
# Markdown Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

# Extra Features
extra:
  generator: false
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/techwithdunamix
    - icon: fontawesome/brands/medium
      link: https://medium.com/@techwithdunamix
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to enhance your experience and analyze traffic. You can adjust your preferences at any time.
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Help us improve by providing suggestions.
extra_javascript:
  - https://cdn.tailwindcss.com

copyright: Copyright &copy; 2024 Techwithdunamix
